apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cluster-local-gateway
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap/overlays/application
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: spark/spark-operator/overlays/application
    name: spark-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/spartakus
    name: spartakus
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-ingress-cognito
    name: istio-ingress
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: aws/aws-istio-authz-adaptor/base_v3
    name: aws-istio-authz-adaptor
  plugins:
  - kind: KfAwsPlugin
    metadata:
      name: aws
    spec:
      auth:
        cognito:
          certArn: arn:aws:acm:us-east-1:363152542207:certificate/4c01aabc-330c-43bc-835a-236e1893d05f
          cognitoAppClientId: 6ues7srdbrdhp58pdt5507pkea
          cognitoUserPoolArn:  arn:aws:cognito-idp:us-west-2:363152542207:userpool/us-west-2_zLeJz6FCU
          cognitoUserPoolDomain: auth.cognito.octo-hatteras.com
      region: us-west-2
      enablePodIamPolicy: true
      # If you don't use IAM Role for Service Account, you can still use node instance roles.
      roles:
      - eksctl-kubeflow-us-west-2-nodegro-NodeInstanceRole-14JSBO5D71DTI
      - eksctl-kubeflow-us-west-2-nodegro-NodeInstanceRole-DWV1SKS9EEK1
      - eksctl-kubeflow-us-west-2-nodegro-NodeInstanceRole-L01AUOZS7UUO
      - eksctl-kubeflow-us-west-2-nodegro-NodeInstanceRole-OW01TO0EZD59
      - eksctl-kubeflow-us-west-2-nodegro-NodeInstanceRole-YDPJ0MZLF87L
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  version: v1.2-branch
